### PR TITLE
Get Spree TaxCloud Spree 3 Ready

### PR DESCRIPTION
**Pull request by BenMorganIO**
I did a _lot_ of refactoring and quite a bit of updating to get the specs working. From 1/11 to 9/11.

### CODE REVIEW

**Comment by BenMorganIO** [comment]
Bump

**Comment by brchristian** [comment]
Wow, this looks like some impressive effort.

@JDutil may be more qualified than I to assess how these changes play with 3.0, because I haven't yet caught up on the development of Spree closely post–v. 2.4.

Some of the more uncontroversial commits (e.g., Ruby 1.9.3 syntax) I'm definitely happy to cherry-pick to `master` right away, and also that way the PR isn't quite so monolithic -- meanwhile, @JDutil can you help me give this PR the once-over, with your knowledge of the changes in Spree 3.0?

**Comment by brchristian** [comment]
@BenMorganIO I've cherry-picked a few commits and left some comments on others. If you get a chance to review and rebase your PR onto the current `master` (which will filter out the cherry-picked commits, for instance), I am happy to loop back around in a day or two and continue reviewing/merging this PR.

Thanks for all your hard work!

**Comment by JDutil** [comment]
The changes look okay to me, but it would be helpful to rebase this so the comparison takes what you've cherry-pick already into account.

**Comment by brchristian** [comment]
@BenMorganIO My feeling here is that the best way for us to get these merged is to split this into a couple different PRs. As it stands, we've got like 40+ commits here, some of which address whitespace and conventions of code style, some of which purge old dead code, some of which refactor, some of which update the test suite, some of which address the breaking changes in Spree 3.0.

Rather than have all of those conversations in one giant thread here while all the commits are waiting in the wings, I'd like to tackle these in a series of PRs with the relevant commits grouped together. You good with that?

**Comment by brchristian** [comment]
@BenMorganIO I've merged the vast majority of this work via cherry-picks, and want to say first and foremost thank you for all the hard work and the excellent contributions.

It looks like there are still some issues getting the specs up and running in Spree 3.0 -- at the moment I'm not able to complete the checkout flow due to what looks like an error coming from calculating the shipping rates (which might be out of scope for this extension), but will need to diagnose that another day.

If there's anything that didn't get merged that you'd like to see merged, throw that into a PR and I'm more than happy to take a look and chat.

With that, I'm going to close this PR as 90%+ merged.

Thank you once again. :+1: :tada:

**Pull request closed without merging**
